# Generated by Django 3.0.7 on 2020-06-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperManager', '0002_auto_20200615_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='filesize',
            field=models.FloatField(verbose_name='File Size (KB)'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Title'),
        ),
    ]
